packages:
- .
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
pnpm:
  overrides:
    postcss: ^8.5.10
  packageImportMethod: clone-or-copy
  allowBuilds:
    esbuild: true
    sharp: true
    unrs-resolver: true
